config/routes.rb
Rails.application.routes.draw do
  resources :account_statuses
  resources :balances
  resources :payments
  resources :accounts
  root 'accounts#index'

end

app/controllers/account_statuses_controller.rb
class AccountStatusesController < ApplicationController
  before_action :set_account_status, only: [:show, :edit, :update, :destroy]

  # GET /account_statuses
  # GET /account_statuses.json
  def index
    @account_statuses = AccountStatus.all
  end

  # GET /account_statuses/1
  # GET /account_statuses/1.json
  def show
  end

  # GET /account_statuses/new
  def new
    @account_status = AccountStatus.new
  end

  # GET /account_statuses/1/edit
  def edit
  end

  # POST /account_statuses
  # POST /account_statuses.json
  def create
    @account_status = AccountStatus.new(account_status_params)

    respond_to do |format|
      if @account_status.save
        format.html { redirect_to @account_status, notice: 'Account status was successfully created.' }
        format.json { render :show, status: :created, location: @account_status }
      else
        format.html { render :new }
        format.json { render json: @account_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /account_statuses/1
  # PATCH/PUT /account_statuses/1.json
  def update
    respond_to do |format|
      if @account_status.update(account_status_params)
        format.html { redirect_to @account_status, notice: 'Account status was successfully updated.' }
        format.json { render :show, status: :ok, location: @account_status }
      else
        format.html { render :edit }
        format.json { render json: @account_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /account_statuses/1
  # DELETE /account_statuses/1.json
  def destroy
    @account_status.destroy
    respond_to do |format|
      format.html { redirect_to account_statuses_url, notice: 'Account status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account_status
      @account_status = AccountStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_status_params
      params.require(:account_status).permit(:account_id, :due_date, :overdue)
    end
end

app/helpers/account_statuses_helper.rb
module AccountStatusesHelper
end

app/views/account_statuses/_form.html.erb
<%= form_for(@account_status) do |f| %>
  <% if @account_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account_status.errors.count, "error") %> prohibited this account_status from being saved:</h2>

      <ul>
      <% @account_status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :account_id %><br>
    <%= f.number_field :account_id %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :overdue %><br>
    <%= f.check_box :overdue %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/account_statuses/edit.html.erb
<h1>Editing Account Status</h1>

<%= render 'form' %>

<%= link_to 'Show', @account_status %> |
<%= link_to 'Back', account_statuses_path %>

app/views/account_statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Account Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Account</th>
      <th>Due date</th>
      <th>Overdue</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @account_statuses.each do |account_status| %>
      <tr>
        <td><%= account_status.account_id %></td>
        <td><%= account_status.due_date %></td>
        <td><%= account_status.overdue %></td>
        <td><%= link_to 'Show', account_status %></td>
        <td><%= link_to 'Edit', edit_account_status_path(account_status) %></td>
        <td><%= link_to 'Destroy', account_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account status', new_account_status_path %>

app/views/account_statuses/new.html.erb
<h1>New Account Status</h1>

<%= render 'form' %>

<%= link_to 'Back', account_statuses_path %>

app/views/account_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <%= @account_status.account_id %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @account_status.due_date %>
</p>

<p>
  <strong>Overdue:</strong>
  <%= @account_status.overdue %>
</p>

<%= link_to 'Edit', edit_account_status_path(@account_status) %> |
<%= link_to 'Back', account_statuses_path %>