config/routes.rb
Rails.application.routes.draw do
  resources :account_statuses
  resources :balances
  resources :payments
  resources :accounts
  root 'accounts#index'

end

app/models/balance.rb
class Balance < ActiveRecord::Base
end

app/controllers/balances_controller.rb
class BalancesController < ApplicationController
  before_action :set_balance, only: [:show, :edit, :update, :destroy]

  # GET /balances
  # GET /balances.json
  def index
    @balances = Balance.all
  end

  # GET /balances/1
  # GET /balances/1.json
  def show
  end

  # GET /balances/new
  def new
    @balance = Balance.new
  end

  # GET /balances/1/edit
  def edit
  end

  # POST /balances
  # POST /balances.json
  def create
    @balance = Balance.new(balance_params)

    respond_to do |format|
      if @balance.save
        format.html { redirect_to @balance, notice: 'Balance was successfully created.' }
        format.json { render :show, status: :created, location: @balance }
      else
        format.html { render :new }
        format.json { render json: @balance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /balances/1
  # PATCH/PUT /balances/1.json
  def update
    respond_to do |format|
      if @balance.update(balance_params)
        format.html { redirect_to @balance, notice: 'Balance was successfully updated.' }
        format.json { render :show, status: :ok, location: @balance }
      else
        format.html { render :edit }
        format.json { render json: @balance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /balances/1
  # DELETE /balances/1.json
  def destroy
    @balance.destroy
    respond_to do |format|
      format.html { redirect_to balances_url, notice: 'Balance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_balance
      @balance = Balance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def balance_params
      params.require(:balance).permit(:account_id, :balance_amount)
    end
end

app/helpers/balances_helper.rb
module BalancesHelper
end

app/views/balances/_form.html.erb
<%= form_for(@balance) do |f| %>
  <% if @balance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@balance.errors.count, "error") %> prohibited this balance from being saved:</h2>

      <ul>
      <% @balance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :account_id %><br>
    <%= f.number_field :account_id %>
  </div>
  <div class="field">
    <%= f.label :balance_amount %><br>
    <%= f.text_field :balance_amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/balances/edit.html.erb
<h1>Editing Balance</h1>

<%= render 'form' %>

<%= link_to 'Show', @balance %> |
<%= link_to 'Back', balances_path %>

app/views/balances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Balances</h1>

<table>
  <thead>
    <tr>
      <th>Account</th>
      <th>Balance amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @balances.each do |balance| %>
      <tr>
        <td><%= balance.account_id %></td>
        <td><%= balance.balance_amount %></td>
        <td><%= link_to 'Show', balance %></td>
        <td><%= link_to 'Edit', edit_balance_path(balance) %></td>
        <td><%= link_to 'Destroy', balance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Balance', new_balance_path %>

app/views/balances/new.html.erb
<h1>New Balance</h1>

<%= render 'form' %>

<%= link_to 'Back', balances_path %>

app/views/balances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <%= @balance.account_id %>
</p>

<p>
  <strong>Balance amount:</strong>
  <%= @balance.balance_amount %>
</p>

<%= link_to 'Edit', edit_balance_path(@balance) %> |
<%= link_to 'Back', balances_path %>