config/routes.rb
Rails.application.routes.draw do
  resources :account_statuses
  resources :balances
  resources :payments
  resources :accounts
  root 'accounts#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :payments
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:account_name, :payment_due, :min_payment, :payment_date, :payment_made, :balance)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :account_name %><br>
    <%= f.text_field :account_name %>
  </div>
  <div class="field">
    <%= f.label :payment_due %><br>
    <%= f.date_select :payment_due %>
  </div>
  <div class="field">
    <%= f.label :min_payment %><br>
    <%= f.text_field :min_payment %>
  </div>
  <div class="field">
    <%= f.label :payment_date %><br>
    <%= f.date_select :payment_date %>
  </div>
  <div class="field">
    <%= f.label :payment_made %><br>
    <%= f.text_field :payment_made %>
  </div>
  <div class="field">
    <%= f.label :balance %><br>
    <%= f.text_field :balance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Account name</th>
      <th>Payment due</th>
      <th>Min payment</th>
      <th>Payment date</th>
      <th>Payment made</th>
      <th>Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.account_name %></td>
        <td><%= account.payment_due %></td>
        <td><%= account.min_payment %></td>
        <td><%= account.payment_date %></td>
        <td><%= account.payment_made %></td>
        <td><%= account.balance %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account name:</strong>
  <%= @account.account_name %>
</p>

<p>
  <strong>Payment due:</strong>
  <%= @account.payment_due %>
</p>

<p>
  <strong>Min payment:</strong>
  <%= @account.min_payment %>
</p>

<p>
  <strong>Payment date:</strong>
  <%= @account.payment_date %>
</p>

<p>
  <strong>Payment made:</strong>
  <%= @account.payment_made %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @account.balance %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>